### PR TITLE
Added GUI components fix #4

### LINKED ISSUE #4: Add the GUI to the game
Who loves terminal mode games? No one  
So, enhance the game so that it can draw the audience. Add the GUI feature.

### PR DESCRIPTION
**Pull request by ShreyasDobhal**
Added interactive layout with buttons and input fields for control
and other Dialog Boxes for results of the game

### CODE REVIEW

**Comment by urdarinda** [comment]
Sorry, you need to follow the proper guidelines while contributing.
* Create a new branch. Changes from the master branch won't be accepted
* If you are adding a new feature listed under issues/features, you need to reference it.

**Comment by shisen404** [comment]
It will be better if you can follow the issue list sequentially. I will appreciate if logical and exceptional errors are resolved first.

**Comment by ShreyasDobhal** [comment]
Sir,
Thanks for response, will keep in mind the next time
but do I have to correct that for this too or its ok

**Comment by urdarinda** [comment]
@ShreyasDobhal Yes, you will need to follow the proper guideline this time too. Please correct that

**Comment by ShreyasDobhal** [comment]
Sir,
It would be great if you could tell me how to do it.
I do not have to Fork it first and then pull request ?

**Pull request closed without merging**
